FROM node
MAINTAINER Ryan Keller <rykeller@uw.edu>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
RUN npm install --quiet
COPY . /usr/src/app

ENV NODE_ENV development
ENV MONGO_URL mongodb://192.168.99.100:27017/mern-starter

EXPOSE 8000
CMD ["npm", "start"]
